# Generated by Django 5.1.7 on 2025-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="checkout_request_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("vodacom", "Vodacom M-Pesa"),
                    ("airtel", "Airtel Money"),
                    ("tigo", "Tigo Pesa"),
                ],
                max_length=10,
            ),
        ),
    ]
